// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Credit update untuk backpressure
 */
export class CreditUpdate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreditUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreditUpdate(bb:flatbuffers.ByteBuffer, obj?:CreditUpdate):CreditUpdate {
  return (obj || new CreditUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreditUpdate(bb:flatbuffers.ByteBuffer, obj?:CreditUpdate):CreditUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreditUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Credits to add (positive) or remove (negative)
 */
creditDelta():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

/**
 * Current total credits available
 */
totalCredits():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startCreditUpdate(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCreditDelta(builder:flatbuffers.Builder, creditDelta:number) {
  builder.addFieldInt32(0, creditDelta, 0);
}

static addTotalCredits(builder:flatbuffers.Builder, totalCredits:number) {
  builder.addFieldInt32(1, totalCredits, 0);
}

static endCreditUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCreditUpdate(builder:flatbuffers.Builder, creditDelta:number, totalCredits:number):flatbuffers.Offset {
  CreditUpdate.startCreditUpdate(builder);
  CreditUpdate.addCreditDelta(builder, creditDelta);
  CreditUpdate.addTotalCredits(builder, totalCredits);
  return CreditUpdate.endCreditUpdate(builder);
}

unpack(): CreditUpdateT {
  return new CreditUpdateT(
    this.creditDelta(),
    this.totalCredits()
  );
}


unpackTo(_o: CreditUpdateT): void {
  _o.creditDelta = this.creditDelta();
  _o.totalCredits = this.totalCredits();
}
}

export class CreditUpdateT {
constructor(
  public creditDelta: number = 0,
  public totalCredits: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return CreditUpdate.createCreditUpdate(builder,
    this.creditDelta,
    this.totalCredits
  );
}
}
