"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorClass = void 0;
/**
 * Error classification untuk retry policy
 */
var ErrorClass;
(function (ErrorClass) {
    /**
     * Success - no error
     */
    ErrorClass[ErrorClass["Success"] = 0] = "Success";
    /**
     * Transient error - safe to retry
     */
    ErrorClass[ErrorClass["Transient"] = 1] = "Transient";
    /**
     * Permanent error - do not retry
     */
    ErrorClass[ErrorClass["Permanent"] = 2] = "Permanent";
    /**
     * Rate limited - retry with backoff
     */
    ErrorClass[ErrorClass["RateLimited"] = 3] = "RateLimited";
    /**
     * Timeout - may retry with caution
     */
    ErrorClass[ErrorClass["Timeout"] = 4] = "Timeout";
    /**
     * Invalid request - do not retry
     */
    ErrorClass[ErrorClass["InvalidRequest"] = 5] = "InvalidRequest";
})(ErrorClass || (exports.ErrorClass = ErrorClass = {}));
