// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Error classification untuk retry policy
 */
export enum ErrorClass {
  /**
   * Success - no error
   */
  Success = 0,

  /**
   * Transient error - safe to retry
   */
  Transient = 1,

  /**
   * Permanent error - do not retry
   */
  Permanent = 2,

  /**
   * Rate limited - retry with backoff
   */
  RateLimited = 3,

  /**
   * Timeout - may retry with caution
   */
  Timeout = 4,

  /**
   * Invalid request - do not retry
   */
  InvalidRequest = 5
}
