// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { KeyValue, KeyValueT } from '../../../vastar/connector/ipc/key-value';


/**
 * Request untuk eksekusi operasi connector
 */
export class ExecuteRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ExecuteRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsExecuteRequest(bb:flatbuffers.ByteBuffer, obj?:ExecuteRequest):ExecuteRequest {
  return (obj || new ExecuteRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsExecuteRequest(bb:flatbuffers.ByteBuffer, obj?:ExecuteRequest):ExecuteRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ExecuteRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Unique request ID untuk correlation
 */
requestId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

/**
 * Tenant ID (for multi-tenancy)
 */
tenantId():string|null
tenantId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
tenantId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Workspace ID (optional)
 */
workspaceId():string|null
workspaceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
workspaceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Trace ID untuk distributed tracing
 */
traceId():string|null
traceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
traceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Connector name (e.g., "http", "postgres")
 */
connectorName():string|null
connectorName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
connectorName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Operation name (e.g., "request", "query")
 */
operation():string|null
operation(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
operation(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Deadline absolute timestamp (milliseconds)
 */
deadlineAtMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

/**
 * Payload data (operation-specific)
 */
payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * Optional headers/metadata
 */
headers(index: number, obj?:KeyValue):KeyValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new KeyValue()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

headersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startExecuteRequest(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addRequestId(builder:flatbuffers.Builder, requestId:bigint) {
  builder.addFieldInt64(0, requestId, BigInt('0'));
}

static addTenantId(builder:flatbuffers.Builder, tenantIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, tenantIdOffset, 0);
}

static addWorkspaceId(builder:flatbuffers.Builder, workspaceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, workspaceIdOffset, 0);
}

static addTraceId(builder:flatbuffers.Builder, traceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, traceIdOffset, 0);
}

static addConnectorName(builder:flatbuffers.Builder, connectorNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, connectorNameOffset, 0);
}

static addOperation(builder:flatbuffers.Builder, operationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, operationOffset, 0);
}

static addDeadlineAtMs(builder:flatbuffers.Builder, deadlineAtMs:bigint) {
  builder.addFieldInt64(6, deadlineAtMs, BigInt('0'));
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addHeaders(builder:flatbuffers.Builder, headersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, headersOffset, 0);
}

static createHeadersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHeadersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endExecuteRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // tenant_id
  builder.requiredField(offset, 12) // connector_name
  builder.requiredField(offset, 14) // operation
  return offset;
}

static finishExecuteRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedExecuteRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createExecuteRequest(builder:flatbuffers.Builder, requestId:bigint, tenantIdOffset:flatbuffers.Offset, workspaceIdOffset:flatbuffers.Offset, traceIdOffset:flatbuffers.Offset, connectorNameOffset:flatbuffers.Offset, operationOffset:flatbuffers.Offset, deadlineAtMs:bigint, payloadOffset:flatbuffers.Offset, headersOffset:flatbuffers.Offset):flatbuffers.Offset {
  ExecuteRequest.startExecuteRequest(builder);
  ExecuteRequest.addRequestId(builder, requestId);
  ExecuteRequest.addTenantId(builder, tenantIdOffset);
  ExecuteRequest.addWorkspaceId(builder, workspaceIdOffset);
  ExecuteRequest.addTraceId(builder, traceIdOffset);
  ExecuteRequest.addConnectorName(builder, connectorNameOffset);
  ExecuteRequest.addOperation(builder, operationOffset);
  ExecuteRequest.addDeadlineAtMs(builder, deadlineAtMs);
  ExecuteRequest.addPayload(builder, payloadOffset);
  ExecuteRequest.addHeaders(builder, headersOffset);
  return ExecuteRequest.endExecuteRequest(builder);
}

unpack(): ExecuteRequestT {
  return new ExecuteRequestT(
    this.requestId(),
    this.tenantId(),
    this.workspaceId(),
    this.traceId(),
    this.connectorName(),
    this.operation(),
    this.deadlineAtMs(),
    this.bb!.createScalarList(this.payload.bind(this), this.payloadLength()),
    this.bb!.createObjList(this.headers.bind(this), this.headersLength())
  );
}


unpackTo(_o: ExecuteRequestT): void {
  _o.requestId = this.requestId();
  _o.tenantId = this.tenantId();
  _o.workspaceId = this.workspaceId();
  _o.traceId = this.traceId();
  _o.connectorName = this.connectorName();
  _o.operation = this.operation();
  _o.deadlineAtMs = this.deadlineAtMs();
  _o.payload = this.bb!.createScalarList(this.payload.bind(this), this.payloadLength());
  _o.headers = this.bb!.createObjList(this.headers.bind(this), this.headersLength());
}
}

export class ExecuteRequestT {
constructor(
  public requestId: bigint = BigInt('0'),
  public tenantId: string|Uint8Array|null = null,
  public workspaceId: string|Uint8Array|null = null,
  public traceId: string|Uint8Array|null = null,
  public connectorName: string|Uint8Array|null = null,
  public operation: string|Uint8Array|null = null,
  public deadlineAtMs: bigint = BigInt('0'),
  public payload: (number)[] = [],
  public headers: (KeyValueT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const tenantId = (this.tenantId !== null ? builder.createString(this.tenantId!) : 0);
  const workspaceId = (this.workspaceId !== null ? builder.createString(this.workspaceId!) : 0);
  const traceId = (this.traceId !== null ? builder.createString(this.traceId!) : 0);
  const connectorName = (this.connectorName !== null ? builder.createString(this.connectorName!) : 0);
  const operation = (this.operation !== null ? builder.createString(this.operation!) : 0);
  const payload = ExecuteRequest.createPayloadVector(builder, this.payload);
  const headers = ExecuteRequest.createHeadersVector(builder, builder.createObjectOffsetList(this.headers));

  return ExecuteRequest.createExecuteRequest(builder,
    this.requestId,
    tenantId,
    workspaceId,
    traceId,
    connectorName,
    operation,
    this.deadlineAtMs,
    payload,
    headers
  );
}
}
