"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExecuteRequestT = exports.ExecuteRequest = void 0;
const flatbuffers = __importStar(require("flatbuffers"));
const key_value_1 = require("../../../vastar/connector/ipc/key-value");
/**
 * Request untuk eksekusi operasi connector
 */
class ExecuteRequest {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsExecuteRequest(bb, obj) {
        return (obj || new ExecuteRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsExecuteRequest(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ExecuteRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    /**
     * Unique request ID untuk correlation
     */
    requestId() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint64(this.bb_pos + offset) : BigInt('0');
    }
    tenantId(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    workspaceId(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    traceId(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    connectorName(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    operation(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    /**
     * Deadline absolute timestamp (milliseconds)
     */
    deadlineAtMs() {
        const offset = this.bb.__offset(this.bb_pos, 16);
        return offset ? this.bb.readUint64(this.bb_pos + offset) : BigInt('0');
    }
    /**
     * Payload data (operation-specific)
     */
    payload(index) {
        const offset = this.bb.__offset(this.bb_pos, 18);
        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
    }
    payloadLength() {
        const offset = this.bb.__offset(this.bb_pos, 18);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    payloadArray() {
        const offset = this.bb.__offset(this.bb_pos, 18);
        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
    }
    /**
     * Optional headers/metadata
     */
    headers(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 20);
        return offset ? (obj || new key_value_1.KeyValue()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    }
    headersLength() {
        const offset = this.bb.__offset(this.bb_pos, 20);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    static startExecuteRequest(builder) {
        builder.startObject(9);
    }
    static addRequestId(builder, requestId) {
        builder.addFieldInt64(0, requestId, BigInt('0'));
    }
    static addTenantId(builder, tenantIdOffset) {
        builder.addFieldOffset(1, tenantIdOffset, 0);
    }
    static addWorkspaceId(builder, workspaceIdOffset) {
        builder.addFieldOffset(2, workspaceIdOffset, 0);
    }
    static addTraceId(builder, traceIdOffset) {
        builder.addFieldOffset(3, traceIdOffset, 0);
    }
    static addConnectorName(builder, connectorNameOffset) {
        builder.addFieldOffset(4, connectorNameOffset, 0);
    }
    static addOperation(builder, operationOffset) {
        builder.addFieldOffset(5, operationOffset, 0);
    }
    static addDeadlineAtMs(builder, deadlineAtMs) {
        builder.addFieldInt64(6, deadlineAtMs, BigInt('0'));
    }
    static addPayload(builder, payloadOffset) {
        builder.addFieldOffset(7, payloadOffset, 0);
    }
    static createPayloadVector(builder, data) {
        builder.startVector(1, data.length, 1);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addInt8(data[i]);
        }
        return builder.endVector();
    }
    static startPayloadVector(builder, numElems) {
        builder.startVector(1, numElems, 1);
    }
    static addHeaders(builder, headersOffset) {
        builder.addFieldOffset(8, headersOffset, 0);
    }
    static createHeadersVector(builder, data) {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }
    static startHeadersVector(builder, numElems) {
        builder.startVector(4, numElems, 4);
    }
    static endExecuteRequest(builder) {
        const offset = builder.endObject();
        builder.requiredField(offset, 6); // tenant_id
        builder.requiredField(offset, 12); // connector_name
        builder.requiredField(offset, 14); // operation
        return offset;
    }
    static finishExecuteRequestBuffer(builder, offset) {
        builder.finish(offset);
    }
    static finishSizePrefixedExecuteRequestBuffer(builder, offset) {
        builder.finish(offset, undefined, true);
    }
    static createExecuteRequest(builder, requestId, tenantIdOffset, workspaceIdOffset, traceIdOffset, connectorNameOffset, operationOffset, deadlineAtMs, payloadOffset, headersOffset) {
        ExecuteRequest.startExecuteRequest(builder);
        ExecuteRequest.addRequestId(builder, requestId);
        ExecuteRequest.addTenantId(builder, tenantIdOffset);
        ExecuteRequest.addWorkspaceId(builder, workspaceIdOffset);
        ExecuteRequest.addTraceId(builder, traceIdOffset);
        ExecuteRequest.addConnectorName(builder, connectorNameOffset);
        ExecuteRequest.addOperation(builder, operationOffset);
        ExecuteRequest.addDeadlineAtMs(builder, deadlineAtMs);
        ExecuteRequest.addPayload(builder, payloadOffset);
        ExecuteRequest.addHeaders(builder, headersOffset);
        return ExecuteRequest.endExecuteRequest(builder);
    }
    unpack() {
        return new ExecuteRequestT(this.requestId(), this.tenantId(), this.workspaceId(), this.traceId(), this.connectorName(), this.operation(), this.deadlineAtMs(), this.bb.createScalarList(this.payload.bind(this), this.payloadLength()), this.bb.createObjList(this.headers.bind(this), this.headersLength()));
    }
    unpackTo(_o) {
        _o.requestId = this.requestId();
        _o.tenantId = this.tenantId();
        _o.workspaceId = this.workspaceId();
        _o.traceId = this.traceId();
        _o.connectorName = this.connectorName();
        _o.operation = this.operation();
        _o.deadlineAtMs = this.deadlineAtMs();
        _o.payload = this.bb.createScalarList(this.payload.bind(this), this.payloadLength());
        _o.headers = this.bb.createObjList(this.headers.bind(this), this.headersLength());
    }
}
exports.ExecuteRequest = ExecuteRequest;
class ExecuteRequestT {
    constructor(requestId = BigInt('0'), tenantId = null, workspaceId = null, traceId = null, connectorName = null, operation = null, deadlineAtMs = BigInt('0'), payload = [], headers = []) {
        this.requestId = requestId;
        this.tenantId = tenantId;
        this.workspaceId = workspaceId;
        this.traceId = traceId;
        this.connectorName = connectorName;
        this.operation = operation;
        this.deadlineAtMs = deadlineAtMs;
        this.payload = payload;
        this.headers = headers;
    }
    pack(builder) {
        const tenantId = (this.tenantId !== null ? builder.createString(this.tenantId) : 0);
        const workspaceId = (this.workspaceId !== null ? builder.createString(this.workspaceId) : 0);
        const traceId = (this.traceId !== null ? builder.createString(this.traceId) : 0);
        const connectorName = (this.connectorName !== null ? builder.createString(this.connectorName) : 0);
        const operation = (this.operation !== null ? builder.createString(this.operation) : 0);
        const payload = ExecuteRequest.createPayloadVector(builder, this.payload);
        const headers = ExecuteRequest.createHeadersVector(builder, builder.createObjectOffsetList(this.headers));
        return ExecuteRequest.createExecuteRequest(builder, this.requestId, tenantId, workspaceId, traceId, connectorName, operation, this.deadlineAtMs, payload, headers);
    }
}
exports.ExecuteRequestT = ExecuteRequestT;
