// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ErrorClass } from '../../../vastar/connector/ipc/error-class';


/**
 * Response dari connector
 */
export class ExecuteResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ExecuteResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsExecuteResponse(bb:flatbuffers.ByteBuffer, obj?:ExecuteResponse):ExecuteResponse {
  return (obj || new ExecuteResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsExecuteResponse(bb:flatbuffers.ByteBuffer, obj?:ExecuteResponse):ExecuteResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ExecuteResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Request ID yang sama dengan request
 */
requestId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

/**
 * Success atau error
 */
errorClass():ErrorClass {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ErrorClass.Success;
}

/**
 * Error message jika gagal
 */
errorMessage():string|null
errorMessage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
errorMessage(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Response payload jika sukses
 */
payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * Execution duration (microseconds)
 */
durationUs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startExecuteResponse(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addRequestId(builder:flatbuffers.Builder, requestId:bigint) {
  builder.addFieldInt64(0, requestId, BigInt('0'));
}

static addErrorClass(builder:flatbuffers.Builder, errorClass:ErrorClass) {
  builder.addFieldInt8(1, errorClass, ErrorClass.Success);
}

static addErrorMessage(builder:flatbuffers.Builder, errorMessageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, errorMessageOffset, 0);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addDurationUs(builder:flatbuffers.Builder, durationUs:bigint) {
  builder.addFieldInt64(4, durationUs, BigInt('0'));
}

static endExecuteResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createExecuteResponse(builder:flatbuffers.Builder, requestId:bigint, errorClass:ErrorClass, errorMessageOffset:flatbuffers.Offset, payloadOffset:flatbuffers.Offset, durationUs:bigint):flatbuffers.Offset {
  ExecuteResponse.startExecuteResponse(builder);
  ExecuteResponse.addRequestId(builder, requestId);
  ExecuteResponse.addErrorClass(builder, errorClass);
  ExecuteResponse.addErrorMessage(builder, errorMessageOffset);
  ExecuteResponse.addPayload(builder, payloadOffset);
  ExecuteResponse.addDurationUs(builder, durationUs);
  return ExecuteResponse.endExecuteResponse(builder);
}

unpack(): ExecuteResponseT {
  return new ExecuteResponseT(
    this.requestId(),
    this.errorClass(),
    this.errorMessage(),
    this.bb!.createScalarList(this.payload.bind(this), this.payloadLength()),
    this.durationUs()
  );
}


unpackTo(_o: ExecuteResponseT): void {
  _o.requestId = this.requestId();
  _o.errorClass = this.errorClass();
  _o.errorMessage = this.errorMessage();
  _o.payload = this.bb!.createScalarList(this.payload.bind(this), this.payloadLength());
  _o.durationUs = this.durationUs();
}
}

export class ExecuteResponseT {
constructor(
  public requestId: bigint = BigInt('0'),
  public errorClass: ErrorClass = ErrorClass.Success,
  public errorMessage: string|Uint8Array|null = null,
  public payload: (number)[] = [],
  public durationUs: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const errorMessage = (this.errorMessage !== null ? builder.createString(this.errorMessage!) : 0);
  const payload = ExecuteResponse.createPayloadVector(builder, this.payload);

  return ExecuteResponse.createExecuteResponse(builder,
    this.requestId,
    this.errorClass,
    errorMessage,
    payload,
    this.durationUs
  );
}
}
