// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Health check response
 */
export class HealthCheckResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HealthCheckResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHealthCheckResponse(bb:flatbuffers.ByteBuffer, obj?:HealthCheckResponse):HealthCheckResponse {
  return (obj || new HealthCheckResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHealthCheckResponse(bb:flatbuffers.ByteBuffer, obj?:HealthCheckResponse):HealthCheckResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HealthCheckResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Is healthy
 */
healthy():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * Status message
 */
message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Current active requests
 */
activeRequests():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * Available credits
 */
availableCredits():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startHealthCheckResponse(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addHealthy(builder:flatbuffers.Builder, healthy:boolean) {
  builder.addFieldInt8(0, +healthy, +false);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static addActiveRequests(builder:flatbuffers.Builder, activeRequests:number) {
  builder.addFieldInt32(2, activeRequests, 0);
}

static addAvailableCredits(builder:flatbuffers.Builder, availableCredits:number) {
  builder.addFieldInt32(3, availableCredits, 0);
}

static endHealthCheckResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHealthCheckResponse(builder:flatbuffers.Builder, healthy:boolean, messageOffset:flatbuffers.Offset, activeRequests:number, availableCredits:number):flatbuffers.Offset {
  HealthCheckResponse.startHealthCheckResponse(builder);
  HealthCheckResponse.addHealthy(builder, healthy);
  HealthCheckResponse.addMessage(builder, messageOffset);
  HealthCheckResponse.addActiveRequests(builder, activeRequests);
  HealthCheckResponse.addAvailableCredits(builder, availableCredits);
  return HealthCheckResponse.endHealthCheckResponse(builder);
}

unpack(): HealthCheckResponseT {
  return new HealthCheckResponseT(
    this.healthy(),
    this.message(),
    this.activeRequests(),
    this.availableCredits()
  );
}


unpackTo(_o: HealthCheckResponseT): void {
  _o.healthy = this.healthy();
  _o.message = this.message();
  _o.activeRequests = this.activeRequests();
  _o.availableCredits = this.availableCredits();
}
}

export class HealthCheckResponseT {
constructor(
  public healthy: boolean = false,
  public message: string|Uint8Array|null = null,
  public activeRequests: number = 0,
  public availableCredits: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const message = (this.message !== null ? builder.createString(this.message!) : 0);

  return HealthCheckResponse.createHealthCheckResponse(builder,
    this.healthy,
    message,
    this.activeRequests,
    this.availableCredits
  );
}
}
