"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageType = void 0;
/**
 * Message type untuk frame header
 */
var MessageType;
(function (MessageType) {
    /**
     * Execute operation request
     */
    MessageType[MessageType["ExecuteRequest"] = 0] = "ExecuteRequest";
    /**
     * Execute operation response
     */
    MessageType[MessageType["ExecuteResponse"] = 1] = "ExecuteResponse";
    /**
     * Health check ping
     */
    MessageType[MessageType["HealthCheck"] = 2] = "HealthCheck";
    /**
     * Health check response
     */
    MessageType[MessageType["HealthResponse"] = 3] = "HealthResponse";
    /**
     * Credit update (backpressure)
     */
    MessageType[MessageType["CreditUpdate"] = 4] = "CreditUpdate";
})(MessageType || (exports.MessageType = MessageType = {}));
