// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Message type untuk frame header
 */
export enum MessageType {
  /**
   * Execute operation request
   */
  ExecuteRequest = 0,

  /**
   * Execute operation response
   */
  ExecuteResponse = 1,

  /**
   * Health check ping
   */
  HealthCheck = 2,

  /**
   * Health check response
   */
  HealthResponse = 3,

  /**
   * Credit update (backpressure)
   */
  CreditUpdate = 4
}
